config/routes.rb
ImBored::Application.routes.draw do
  resources :events

end

app/models/event.rb
class Event
    attr_accessor :title, :location, :description, :event_time, :id, :distance, :rank

    def self.all(options)
        
        return APIHandler.get_events(options) 
    end
    
    def initialize(attributes = {})
        self.id = attributes[:id]
        self.title = attributes[:title]
        self.description = attributes[:description]
        self.location = attributes[:location]
        self.event_time = attributes[:event_time]
        self.distance = attributes[:distance]
        self.rank = attributes[:rank]
     end

    def read_attribute_for_validation(key)
        @attributes[key]
    end

    def self.find(param)
        return APIHandler.get_event(param[:id]) 
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  def index

    # If the required parameters are missing give 400
    if params[:longitude] == nil or params[:latitude] == nil then
        render_error("400")
        return
    end

    options  = {
      :longitude => params[:longitude], 
      :latitude => params[:latitude],
      :distance => params[:distance]
    }

    @events = Event.all(options)
  
    if @events.length > 0 then
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @events, :callback => params[:callback] }
      end
    else
        # If no events was found
        render_error("204")
    end
  end


  def render_error(code)
    if code == "204" then
      respond_to do |format|
        puts "204!"
        format.html { render :file => "#{Rails.root}/public/204.html", :status => :no_content }
        format.json { head :no_content }
      end
    elsif code == "400" then
      respond_to do |format|
        puts "400!"
        format.html { render :file => "#{Rails.root}/public/400.html", :status => :bad_request }
        format.json { head :bad_request }
      end
    end   
  end


  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params)
    if @event == nil then
        render_error("204")
    else
        respond_to do |format|
          format.html # show.html.erb
          format.json  { render :json => @event }
        end
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titel %><br />
    <%= f.text_field :titel %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :startTime %><br />
    <%= f.text_field :startTime %>
  </div>
  <div class="field">
    <%= f.label :endTime %><br />
    <%= f.text_field :endTime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Titel</th>
    <th>Location</th>
    <th>Description</th>
    <th>Starttime</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td> 
		<ul>
			<li><%= event.location[:street] %></li>
			<li><%= event.location[:postal_code] %></li>
			<li><%= event.location[:city] %></li>
			<li><%= event.location[:contry] %></li>
		</ul>
	</td>
    <td><%= event.description %></td>
    <td><%= event.event_time %></td>
  </tr>
<% end %>
</table>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1>Single event</h1>
<h2><%= @event.title %></h2>
<ul>
    <li><%= @event.location[:street] %></li>
    <li><%= @event.location[:postal_code] %></li>
    <li><%= @event.location[:city] %></li>
    <li><%= @event.location[:contry] %></li>
    <td><%= @event.description %></li>
    <td><%= @event.event_time %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImBored</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>